# 使用多层感知机创建softmax多分类器

In [1]:
%matplotlib inline

/Users/innovation_mbp/anaconda/envs/tensorflow/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


In [2]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

Using TensorFlow backend.


In [3]:
# Generate dummy data
import numpy as np
x_train = np.random.random((1000, 20))
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
x_test = np.random.random((100, 20))
y_test = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)

* keras.utils.to_categorical
源码介绍如下：

```
Converts a class vector (integers) to binary class matrix. 
E.g. for use with categorical_crossentropy.
```

将一个整数类型的向量，转换成二进制类型的举证

其参数描述如下：

```
def to_categorical(y, num_classes=None): 
Arguments 
y: class vector to be converted into a matrix 
(integers from 0 to num_classes). 
num_classes: total number of classes.
```

y是值为0-num_classes的整数向量

在上例中，

```
y_train = keras.utils.to_categorical(np.random.randint(10, size=(1000, 1)), num_classes=10)
```

表示首先产生shape=（1000,1)的整数向量，然后将整数向量转换成（1000，10）的二进制矩阵，可以用如下语句进行测试。

In [4]:
intVector = np.random.randint(5,size=(3,1))
print intVector.shape
print intVector
biaMatrix = keras.utils.to_categorical(intVector,num_classes=5)
print biaMatrix.shape
print biaMatrix

(3, 1)
[[4]
 [2]
 [0]]
(3, 5)
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.]]


In [5]:
model = Sequential()
# Dense(64) is a fully-connected layer with 64 hidden units.
# in the first layer, you must specify the expected input data shape:
# here, 20-dimensional vectors.
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

* 神经网络结构

网络采用Keras惯序模型，第一层是64个神经元的全连接层，输入数据为20维向量，激活函数为“relu”

第二层为Dropout层，丢弃概率为0.5

第三层为64个神经元的全连接层

第四层是Dropout层，丢弃概率为0.5

第五层是输出层，具有10个输出神经元，激活函数是softmax

In [6]:
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=20,
          batch_size=128)

Epoch 1/20
1000/1000 [==============================] - 0s - loss: 2.3469 - acc: 0.1030     
Epoch 2/20
1000/1000 [==============================] - 0s - loss: 2.3412 - acc: 0.0920     
Epoch 3/20
1000/1000 [==============================] - 0s - loss: 2.3358 - acc: 0.0960     
Epoch 4/20
1000/1000 [==============================] - 0s - loss: 2.3363 - acc: 0.0950     
Epoch 5/20
1000/1000 [==============================] - 0s - loss: 2.3169 - acc: 0.1010     
Epoch 6/20
1000/1000 [==============================] - 0s - loss: 2.3134 - acc: 0.1250     
Epoch 7/20
1000/1000 [==============================] - 0s - loss: 2.3156 - acc: 0.1040     
Epoch 8/20
1000/1000 [==============================] - 0s - loss: 2.3109 - acc: 0.1120     
Epoch 9/20
1000/1000 [==============================] - 0s - loss: 2.3136 - acc: 0.1100     
Epoch 10/20
1000/1000 [==============================] - 0s - loss: 2.3070 - acc: 0.1110     
Epoch 11/20
1000/1000 [==============================] - 0s - loss: 2

In [7]:
score = model.evaluate(x_test, y_test, batch_size=128)
print score

100/100 [==============================] - 0s
[2.3086214065551758, 0.10999999940395355]


In [8]:
output = model.predict(x_test)
print output.shape
print np.argmax(output,axis=1)
print keras.utils.to_categorical(np.argmax(output,axis=1),num_classes=10)

(100, 10)
[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 8
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0

NameError: name 'max_features' is not defined